##############
# 最全示例配置 #
##############
#各项路径配置
[location]
projects = "/home/zido/java/projects"
bin = "/home/zido/java/bin"
log = "/home/zido/java/logs"
tmp = "/home/zido/java/bin/.temps"
java = "java"

#git相关配置
[git]
remote = "origin"
branch = "master"
prefix = "git@github.com/xxx"
name = "zido"
email = "wuhongxu1208@gmail.com"
username = "wuhongxu1208@gmail.com"
password = "xxx"
#maven相关配置
[maven]
bin = "mvn"
repository = "/home/zido/.m2/repository"
#打包相关配置
[package]
env = "test"
target = "target" #relative dir
#依赖相关配置
[dependencies]
update = ["site.zido:demo:0.0.1"]
